### ISSUE TITLE
Align project name and configuration namespace

### ISSUE THREAD

**Issue by snicoll** [icha024/spring-boot-starter-cloudant#1]
As requested [in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) please do not prefix your starter with `spring-boot`. Also, if you expose configuration keys (you do), do not use our prefixes (typically `spring.data.cloudant` should be `cloudant`).

**Comment by icha024** [comment]
Fixed. The repo has been moved to the suggest name and config renamed.
I'll update the PR for doc change.

**Comment by snicoll** [comment]
@icha024 it's a bit late now but you know you can rename a git repo?

**Comment by icha024** [comment]
... I didn't know that. Ah well, will do that next time instead. Thanks for the tip!
